name: test-environment
channels:
  - conda-forge
dependencies:
  # required dependencies
  - python=3.7
  - pyyaml
  - cloudpickle=1.1.1
  - partd=0.3.10
  - fsspec=0.6.0
  - toolz=0.8.2
  # test dependencies
  - pytest
  - pytest-rerunfailures
  - pytest-xdist
