name: CI Additional

on: [push, pull_request]

jobs:
  mindeps:
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        environment: ["mindeps-array-dataframe", "mindeps-non-optional", "mindeps-distributed"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          python-version: "3.7"
          environment-file: continuous_integration/environment-${{ matrix.environment }}.yaml
          activate-environment: test-environment
          auto-activate-base: false

      - name: Install
        shell: bash -l {0}
        run: source continuous_integration/scripts/install.sh

      - name: Run tests
        shell: bash -l {0}
        run: source continuous_integration/scripts/run_tests.sh

  hdfs:
    runs-on: "ubuntu-latest"
    if: "contains(github.event.head_commit.message, 'test-hdfs') || github.event_name != 'pull_request'"

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Start HDFS
        shell: bash -l {0}
        run: source continuous_integration/hdfs/startup_hdfs.sh

      - name: Install
        shell: bash -l {0}
        run: source continuous_integration/hdfs/install.sh

      - name: Run tests
        shell: bash -l {0}
        run: source continuous_integration/hdfs/run_tests.sh

  doctest:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          python-version: "3.8"
          environment-file: continuous_integration/environment-latest.yaml
          activate-environment: test-environment
          auto-activate-base: false

      - name: Install
        shell: bash -l {0}
        run: source continuous_integration/scripts/install.sh

      - name: Run tests
        shell: bash -l {0}
        run: pytest -v --doctest-modules --ignore-glob='*/test_*.py' dask

  imports:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          python-version: "3.7"
          activate-environment: test-environment
          auto-activate-base: false

      - name: Run import tests
        shell: bash -l {0}
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: source continuous_integration/scripts/test_imports.sh
